name: Manager
version: '${project.version}'
main: lemmensthijmen.manager.Main
api-version: 1.17
commands:
  area:
    description: area command
    aliases:
      - join
      - leave
      - reset
  test:
    description: test command
